In [ ]:
#https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data?select=test.csv
#test.csv содержит информацию о домах на продаже и их характеристиках

In [1]:
import pandas as pd
df = pd.read_csv('test.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [2]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [3]:
df.info

<bound method DataFrame.info of         Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg
1     1462          20       RL         81.0    14267   Pave   NaN      IR1
2     1463          60       RL         74.0    13830   Pave   NaN      IR1
3     1464          60       RL         78.0     9978   Pave   NaN      IR1
4     1465         120       RL         43.0     5005   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub  ...         120        0    NaN  MnPrv
1            Lvl    AllPub  ...           0        0    NaN    NaN
2            Lvl    AllPub  ...           0        0    NaN  MnPrv
3            Lvl    AllPub  ...           0        0    NaN    NaN
4            HLS    AllPub  ...         144        0    NaN    NaN
...          ...       ...  ...         ...      ...    ...    ...
1454         Lvl    AllPub  ...           0        0    NaN    NaN
1455         Lvl    AllPub  ...           0        0    NaN    NaN
1456         Lvl    AllPub  ...           0        0    NaN    NaN
1457         Lvl    AllPub  ...           0        0    NaN  MnPrv
1458         Lvl    AllPub  ...           0        0    NaN    NaN

     MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition
0            NaN       0      6    2010        WD         Normal
1           Gar2   12500      6    2010        WD         Normal
2            NaN       0      3    2010        WD         Normal
3            NaN       0      6    2010        WD         Normal
4            NaN       0      1    2010        WD         Normal
...          ...     ...    ...     ...       ...            ...
1454         NaN       0      6    2006        WD         Normal
1455         NaN       0      4    2006        WD        Abnorml
1456         NaN       0      9    2006        WD        Abnorml
1457        Shed     700      7    2006        WD         Normal
1458         NaN       0     11    2006        WD         Normal

[1459 rows x 80 columns]>

In [4]:
df.shape

(1459, 80)

In [5]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1459.000000,1459.000000,1232.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,...,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,2190.000000,57.378341,68.580357,9819.161069,6.078821,5.553804,1971.357779,1983.662783,100.709141,439.203704,...,472.768861,93.174777,48.313914,24.243317,1.794380,17.064428,1.744345,58.167923,6.104181,2007.769705
std,421.321334,42.746880,22.376841,4955.517327,1.436812,1.113740,30.390071,21.130467,177.625900,455.268042,...,217.048611,127.744882,68.883364,67.227765,20.207842,56.609763,30.491646,630.806978,2.722432,1.301740
min,1461.000000,20.000000,21.000000,1470.000000,1.000000,1.000000,1879.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,1825.500000,20.000000,58.000000,7391.000000,5.000000,5.000000,1953.000000,1963.000000,0.000000,0.000000,...,318.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000
50%,2190.000000,50.000000,67.000000,9399.000000,6.000000,5.000000,1973.000000,1992.000000,0.000000,350.500000,...,480.000000,0.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,2554.500000,70.000000,80.000000,11517.500000,7.000000,6.000000,2001.000000,2004.000000,164.000000,753.500000,...,576.000000,168.000000,72.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,2919.000000,190.000000,200.000000,56600.000000,10.000000,9.000000,2010.000000,2010.000000,1290.000000,4010.000000,...,1488.000000,1424.000000,742.000000,1012.000000,360.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000

In [6]:
print(df.describe(include="str"))

       MSZoning Street Alley LotShape LandContour Utilities LotConfig  \
count      1455   1459   107     1459        1459      1457      1459
unique        5      2     2        4           4         1         5
top          RL   Pave  Grvl      Reg         Lvl    AllPub    Inside
freq       1114   1453    70      934        1311      1457      1081

       LandSlope Neighborhood Condition1  ... GarageType GarageFinish  \
count       1459         1459       1459  ...       1383         1381
unique         3           25          9  ...          6            3
top          Gtl        NAmes       Norm  ...     Attchd          Unf
freq        1396          218       1251  ...        853          625

       GarageQual GarageCond PavedDrive PoolQC  Fence MiscFeature SaleType  \
count        1381       1381       1459      3    290          51     1458
unique          4          5          3      2      4           3        9
top            TA         TA          Y     Ex  MnPrv        Shed       WD
freq         1293       1328       1301      2    172          46     1258

       SaleCondition
count           1459
unique             6
top           Normal
freq            1204

[4 rows x 43 columns]

In [7]:
print(df.isnull())

         Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0     False       False     False        False    False   False   True
1     False       False     False        False    False   False   True
2     False       False     False        False    False   False   True
3     False       False     False        False    False   False   True
4     False       False     False        False    False   False   True
...     ...         ...       ...          ...      ...     ...    ...
1454  False       False     False        False    False   False   True
1455  False       False     False        False    False   False   True
1456  False       False     False        False    False   False   True
1457  False       False     False        False    False   False   True
1458  False       False     False        False    False   False   True

      LotShape  LandContour  Utilities  ...  ScreenPorch  PoolArea  PoolQC  \
0        False        False      False  ...        False     False    True
1        False        False      False  ...        False     False    True
2        False        False      False  ...        False     False    True
3        False        False      False  ...        False     False    True
4        False        False      False  ...        False     False    True
...        ...          ...        ...  ...          ...       ...     ...
1454     False        False      False  ...        False     False    True
1455     False        False      False  ...        False     False    True
1456     False        False      False  ...        False     False    True
1457     False        False      False  ...        False     False    True
1458     False        False      False  ...        False     False    True

      Fence  MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition
0     False         True    False   False   False     False          False
1      True        False    False   False   False     False          False
2     False         True    False   False   False     False          False
3      True         True    False   False   False     False          False
4      True         True    False   False   False     False          False
...     ...          ...      ...     ...     ...       ...            ...
1454   True         True    False   False   False     False          False
1455   True         True    False   False   False     False          False
1456   True         True    False   False   False     False          False
1457  False        False    False   False   False     False          False
1458   True         True    False   False   False     False          False

[1459 rows x 80 columns]

In [8]:
print(df['GarageArea'].sum())#сумма всех площадей, занятых под гаражи

689297.0

In [9]:
print(df['YrSold'].duplicated())#повторение года продажи

0       False
1        True
2        True
3        True
4        True
        ...
1454     True
1455     True
1456     True
1457     True
1458     True
Name: YrSold, Length: 1459, dtype: bool

In [10]:
print(df.dropna(subset = ['Alley']))# удаление данных о домах без аллеи

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
36    1497         160       FV         39.0     3515   Pave  Pave      Reg
37    1498         160       FV         30.0     3215   Pave  Pave      Reg
38    1499         160       FV         24.0     2544   Pave  Pave      Reg
39    1500         160       FV         24.0     2544   Pave  Pave      Reg
42    1503          20       FV         57.0    12853   Pave  Pave      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1330  2791          20       RM         65.0     9750   Pave  Grvl      Reg
1335  2796          30       RL         50.0    11672   Pave  Pave      IR2
1337  2798          50       RM         60.0    10320   Pave  Grvl      Reg
1410  2871          50       RL         45.0     8248   Pave  Grvl      Reg
1411  2872          30       RL         60.0     8088   Pave  Grvl      Reg

     LandContour Utilities  ... ScreenPorch PoolArea PoolQC Fence MiscFeature  \
36           Lvl    AllPub  ...           0        0    NaN   NaN         NaN
37           Lvl    AllPub  ...           0        0    NaN   NaN         NaN
38           Lvl    AllPub  ...           0        0    NaN   NaN         NaN
39           Lvl    AllPub  ...           0        0    NaN   NaN         NaN
42           Lvl    AllPub  ...           0        0    NaN   NaN         NaN
...          ...       ...  ...         ...      ...    ...   ...         ...
1330         Lvl    AllPub  ...           0        0    NaN   NaN        Gar2
1335         Lvl    AllPub  ...           0        0    NaN   NaN         NaN
1337         Lvl    AllPub  ...         210        0    NaN   NaN         NaN
1410         Lvl    AllPub  ...           0        0    NaN   NaN         NaN
1411         Lvl    AllPub  ...           0        0    NaN   NaN         NaN

     MiscVal MoSold  YrSold  SaleType  SaleCondition
36         0      1    2010        WD         Normal
37         0      4    2010     ConLD         Normal
38         0      2    2010        WD         Normal
39         0      5    2010        WD         Normal
42         0      4    2010       New        Partial
...      ...    ...     ...       ...            ...
1330    4500      7    2006        WD         Normal
1335       0      7    2006        WD         Normal
1337       0     10    2006        WD        Abnorml
1410       0      9    2006       COD        Abnorml
1411       0      2    2006     ConLD         Normal

[107 rows x 80 columns]

In [11]:
print(df.iloc[:, 0:10])# вывод данных по первым 10 столбцам

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg
1     1462          20       RL         81.0    14267   Pave   NaN      IR1
2     1463          60       RL         74.0    13830   Pave   NaN      IR1
3     1464          60       RL         78.0     9978   Pave   NaN      IR1
4     1465         120       RL         43.0     5005   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1454  2915         160       RM         21.0     1936   Pave   NaN      Reg
1455  2916         160       RM         21.0     1894   Pave   NaN      Reg
1456  2917          20       RL        160.0    20000   Pave   NaN      Reg
1457  2918          85       RL         62.0    10441   Pave   NaN      Reg
1458  2919          60       RL         74.0     9627   Pave   NaN      Reg

     LandContour Utilities
0            Lvl    AllPub
1            Lvl    AllPub
2            Lvl    AllPub
3            Lvl    AllPub
4            HLS    AllPub
...          ...       ...
1454         Lvl    AllPub
1455         Lvl    AllPub
1456         Lvl    AllPub
1457         Lvl    AllPub
1458         Lvl    AllPub

[1459 rows x 10 columns]

In [12]:
#print(df['Alley'].fillna(df['Alley'].describe().top))#замена пустых значений об аллее наиболее встречающимся её видом для усреднения всех значений этого столбца

In [18]:
mode = df['LotFrontage'].mode()
print(df['LotFrontage'].isna().sum(),'\n')#количество пустых ячеек в столбце
print(df['LotFrontage'].fillna(mode))

227

0        80.0
1        81.0
2        74.0
3        78.0
4        43.0
        ...
1454     21.0
1455     21.0
1456    160.0
1457     62.0
1458     74.0
Name: LotFrontage, Length: 1459, dtype: float64

In [34]:
print(df.describe(),'\n') # min, max, квартили и т.д. 
print(df.median(numeric_only = True), '\n')#медиана
print(df.mode(numeric_only = True, axis = 0))# мода

                Id   MSSubClass  LotFrontage       LotArea  OverallQual  \
count  1459.000000  1459.000000  1232.000000   1459.000000  1459.000000
mean   2190.000000    57.378341    68.580357   9819.161069     6.078821
std     421.321334    42.746880    22.376841   4955.517327     1.436812
min    1461.000000    20.000000    21.000000   1470.000000     1.000000
25%    1825.500000    20.000000    58.000000   7391.000000     5.000000
50%    2190.000000    50.000000    67.000000   9399.000000     6.000000
75%    2554.500000    70.000000    80.000000  11517.500000     7.000000
max    2919.000000   190.000000   200.000000  56600.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1459.000000  1459.000000   1459.000000  1444.000000  1458.000000  ...
mean      5.553804  1971.357779   1983.662783   100.709141   439.203704  ...
std       1.113740    30.390071     21.130467   177.625900   455.268042  ...
min       1.000000  1879.000000   1950.000000     0.000000     0.000000  ...
25%       5.000000  1953.000000   1963.000000     0.000000     0.000000  ...
50%       5.000000  1973.000000   1992.000000     0.000000   350.500000  ...
75%       6.000000  2001.000000   2004.000000   164.000000   753.500000  ...
max       9.000000  2010.000000   2010.000000  1290.000000  4010.000000  ...

        GarageArea   WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count  1458.000000  1459.000000  1459.000000    1459.000000  1459.000000
mean    472.768861    93.174777    48.313914      24.243317     1.794380
std     217.048611   127.744882    68.883364      67.227765    20.207842
min       0.000000     0.000000     0.000000       0.000000     0.000000
25%     318.000000     0.000000     0.000000       0.000000     0.000000
50%     480.000000     0.000000    28.000000       0.000000     0.000000
75%     576.000000   168.000000    72.000000       0.000000     0.000000
max    1488.000000  1424.000000   742.000000    1012.000000   360.000000

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold
count  1459.000000  1459.000000   1459.000000  1459.000000  1459.000000
mean     17.064428     1.744345     58.167923     6.104181  2007.769705
std      56.609763    30.491646    630.806978     2.722432     1.301740
min       0.000000     0.000000      0.000000     1.000000  2006.000000
25%       0.000000     0.000000      0.000000     4.000000  2007.000000
50%       0.000000     0.000000      0.000000     6.000000  2008.000000
75%       0.000000     0.000000      0.000000     8.000000  2009.000000
max     576.000000   800.000000  17000.000000    12.000000  2010.000000

[8 rows x 37 columns]

Id               2190.0
MSSubClass         50.0
LotFrontage        67.0
LotArea          9399.0
OverallQual         6.0
OverallCond         5.0
YearBuilt        1973.0
YearRemodAdd     1992.0
MasVnrArea          0.0
BsmtFinSF1        350.5
BsmtFinSF2          0.0
BsmtUnfSF         460.0
TotalBsmtSF       988.0
1stFlrSF         1079.0
2ndFlrSF            0.0
LowQualFinSF        0.0
GrLivArea        1432.0
BsmtFullBath        0.0
BsmtHalfBath        0.0
FullBath            2.0
HalfBath            0.0
BedroomAbvGr        3.0
KitchenAbvGr        1.0
TotRmsAbvGrd        6.0
Fireplaces          0.0
GarageYrBlt      1979.0
GarageCars          2.0
GarageArea        480.0
WoodDeckSF          0.0
OpenPorchSF        28.0
EnclosedPorch       0.0
3SsnPorch           0.0
ScreenPorch         0.0
PoolArea            0.0
MiscVal             0.0
MoSold              6.0
YrSold           2008.0
dtype: float64

        Id  MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  \
0     1461        20.0         60.0   9600.0          5.0          5.0
1     1462         NaN          NaN      NaN          NaN          NaN
2     1463         NaN          NaN      NaN          NaN          NaN
3     1464         NaN          NaN      NaN          NaN          NaN
4     1465         NaN          NaN      NaN          NaN          NaN
...    ...         ...          ...      ...          ...          ...
1454  2915         NaN          NaN      NaN          NaN          NaN
1455  2916         NaN          NaN      NaN          NaN          NaN
1456  2917         NaN          NaN      NaN          NaN          NaN
1457  2918         NaN          NaN      NaN          NaN          NaN
1458  2919         NaN          NaN      NaN          NaN          NaN

      YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  ...  GarageArea  \
0        2005.0        1950.0         0.0         0.0  ...         0.0
1           NaN           NaN         NaN         NaN  ...         NaN
2           NaN           NaN         NaN         NaN  ...         NaN
3           NaN           NaN         NaN         NaN  ...         NaN
4           NaN           NaN         NaN         NaN  ...         NaN
...         ...           ...         ...         ...  ...         ...
1454        NaN           NaN         NaN         NaN  ...         NaN
1455        NaN           NaN         NaN         NaN  ...         NaN
1456        NaN           NaN         NaN         NaN  ...         NaN
1457        NaN           NaN         NaN         NaN  ...         NaN
1458        NaN           NaN         NaN         NaN  ...         NaN

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0            0.0          0.0            0.0        0.0          0.0
1            NaN          NaN            NaN        NaN          NaN
2            NaN          NaN            NaN        NaN          NaN
3            NaN          NaN            NaN        NaN          NaN
4            NaN          NaN            NaN        NaN          NaN
...          ...          ...            ...        ...          ...
1454         NaN          NaN            NaN        NaN          NaN
1455         NaN          NaN            NaN        NaN          NaN
1456         NaN          NaN            NaN        NaN          NaN
1457         NaN          NaN            NaN        NaN          NaN
1458         NaN          NaN            NaN        NaN          NaN

      PoolArea  MiscVal  MoSold  YrSold
0          0.0      0.0     6.0  2007.0
1          NaN      NaN     NaN     NaN
2          NaN      NaN     NaN     NaN
3          NaN      NaN     NaN     NaN
4          NaN      NaN     NaN     NaN
...        ...      ...     ...     ...
1454       NaN      NaN     NaN     NaN
1455       NaN      NaN     NaN     NaN
1456       NaN      NaN     NaN     NaN
1457       NaN      NaN     NaN     NaN
1458       NaN      NaN     NaN     NaN

[1459 rows x 37 columns]

In [55]:
print(df['GarageArea'].quantile([.05,.25,.50,.75,.95]))# перцентили

0.05      0.0
0.25    318.0
0.50    480.0
0.75    576.0
0.95    864.0
Name: GarageArea, dtype: float64